### 1. Testar cadastro de cpf errado 
POST http://localhost:3000/ciclista 
Content-Type: application/json

{
    "nome": "Roberto",
    "email": "roberto@gmail.com",
    "senha": "abc",
    "cpf": "123456789",
    "endereco": "rua abc, 5",
    "celular": "47912345678"
}

### 2. Testar cadastro do ciclista
POST http://localhost:3000/ciclista 
Content-Type: application/json

{
    "nome": "Roberto",
    "email": "roberto@gmail.com",
    "senha": "abc",
    "cpf": "12345678912",
    "endereco": "rua abc, 5",
    "celular": "47912345678"
}

### 3. Testar cadastro do ciclista 2
POST http://localhost:3000/ciclista 
Content-Type: application/json

{
    "nome": "Bruno",
    "email": "bruno@gmail.com",
    "senha": "def",
    "cpf": "98765432198",
    "endereco": "rua def, 10",
    "celular": "47987654321"
}

### 4. Testar login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "bruno@gmail.com",
    "senha": "def"
}